# ==========================================
# Configuración del proyecto CampusFlow
# ==========================================
spring.application.name=campusFlow

# Configuración de Base de Datos MySQL (Soporta variables de entorno con valores por defecto)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/campus?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Alpine123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=INFO
logging.level.com.devsenior.campusFlow=DEBUG
