# Este archivo se encarga de definir la configuracion global de la aplicacion, la conexion a la base de datos MySQL y los parametros de Hibernate/JPA.
# Los datos de configuracion provienen del entorno de ejecucion y van hacia Spring Boot durante el arranque del servidor.

# Nombre de la aplicacion
spring.application.name=vetturno

# Configuracion de conexion a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/vetturno?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Alpine123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
